require "haiwen.plugins-setup"
require "haiwen.core.options"
require "haiwen.core.colorscheme"
require "haiwen.plugins.lualine"
require "haiwen.plugins.bufferline"
require "haiwen.plugins.telescope"
require "haiwen.plugins.treesitter"
require "haiwen.plugins.autopairs"
require "haiwen.plugins.comment"
require "haiwen.plugins.nvim-cmp"
require "haiwen.plugins.nvim-tree"
require "haiwen.plugins.surround"
require "haiwen.plugins.hop"
require "haiwen.plugins.bankline"
require "haiwen.plugins.alpha"
require "haiwen.plugins.gitsigns"
require "haiwen.plugins.neogit"
require "haiwen.plugins.which-key"
require "haiwen.plugins.nvim-ts-autotag"
require "haiwen.plugins.symbols-outline"
require "haiwen.plugins.colorizer"
require "haiwen.plugins.diffview"
require "haiwen.plugins.toggleterm"
require "haiwen.plugins.impatient"

require "haiwen.plugins.lsp.mason"
require "haiwen.plugins.lsp.lspconfig"
require "haiwen.plugins.lsp.lspsaga"

require "haiwen.plugins.dap"


-- Keymap
require "haiwen.core.keymaps"
